name: Build ltsc2022

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      run: |
        $version = '${{ github.ref_name }}'.Substring(1)
        $base = 'mcr.microsoft.com/windows/servercore:ltsc2022'
        docker build -f Dockerfile -t local --build-arg BASE_REF=$base --build-arg REF=${{ github.ref_name }} .
        $tag = "airpower/airpower:$version-windowsservercore-ltsc2022"
        docker image tag local $tag
        docker image push $tag
        $tag = "airpower/airpower:windowsservercore-ltsc2022"
        docker image tag local $tag
        docker image push $tag
