name: Test Airpower

on: [push, pull_request]

jobs:
  pwsh-test:
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Pwsh Test
      run: pwsh.exe .\test.ps1
  powershell-test:
    runs-on: windows-2022
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: PowerShell Test
      run: powershell.exe .\test.ps1
